service: gensym_scribe
image: waferbaby/gemsym_scribe

servers:
  web:
    - waferbaby.com

proxy: false

ssh:
  user: deployer

registry:
  server: registry.digitalocean.com
  username: waferbaby

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "gensym_scribe_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
